import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import ProviderWrapper from '@/clientProviders';

export const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={roboto.className}>
				<ProviderWrapper>{children}</ProviderWrapper>
			</body>
		</html>
	);
}
